impl Default for SimpleWaveformSynth {
    fn default() -> Self {
        Self {
            layers: [OscillatorLayer {
                waveform: Waveform::Sine,
                level: 1.0,
                detune_cents: 0.0,
            }; 4],
            layer_count: 1,
            master_level: 0.8,
            attack_ms: 5.0,
            decay_ms: 100.0,
            sustain: 0.8,
            release_ms: 120.0,
            pitch_shift: 0,
            pan: 0.0,
            mono: false,
            glide_ms: 80.0,
            filter: FilterKind::Off,
            filter_cutoff_hz: 8_000.0,
            filter_resonance: 0.1,
            effects: DEFAULT_EFFECTS,
        }
    }
}

macro_rules! preset {
    ($name:expr, $category:expr, $waveform:expr, $layer_count:expr, $detune:expr,
     $layer_level:expr, $attack:expr, $decay:expr, $sustain:expr, $release:expr,
     $filter:expr, $cutoff:expr $(,)?) => {{
        preset!(
            $name,
            $category,
            $waveform,
            $layer_count,
            $detune,
            $layer_level,
            $attack,
            $decay,
            $sustain,
            $release,
            0,
            $filter,
            $cutoff
        )
    }};
    ($name:expr, $category:expr, $waveform:expr, $layer_count:expr, $detune:expr,
     $layer_level:expr, $attack:expr, $decay:expr, $sustain:expr, $release:expr,
     $pitch:expr, $filter:expr, $cutoff:expr $(,)?) => {{
        let mut layers = [OscillatorLayer {
            waveform: $waveform,
            level: $layer_level,
            detune_cents: 0.0,
        }; 4];
        layers[0].detune_cents = if $layer_count > 1 { -$detune } else { 0.0 };
        layers[1].detune_cents = $detune;
        layers[2].detune_cents = -$detune * 0.45;
        layers[3].detune_cents = $detune * 0.45;
        SynthPreset {
            name: $name,
            category: $category,
            synth: SimpleWaveformSynth {
                layers,
                layer_count: $layer_count,
                master_level: 0.8,
                attack_ms: $attack,
                decay_ms: $decay,
                sustain: $sustain,
                release_ms: $release,
                pitch_shift: $pitch,
                pan: 0.0,
                mono: false,
                glide_ms: 80.0,
                filter: $filter,
                filter_cutoff_hz: $cutoff,
                filter_resonance: 0.15,
                effects: DEFAULT_EFFECTS,
            },
        }
    }};
}

const fn snare_preset() -> SynthPreset {
    let mut preset = preset!(
        "Snare drum",
        "Percussion",
        Waveform::Noise,
        3,
        0.0,
        0.7,
        0.0,
        120.0,
        0.0,
        80.0,
        -5,
        FilterKind::LowPass,
        7_500.0,
    );
    preset.synth.master_level = 0.9;
    preset.synth.filter_resonance = 0.05;
    preset.synth.layers[0] = OscillatorLayer {
        waveform: Waveform::Sine,
        level: 0.8,
        detune_cents: 0.0,
    };
    preset.synth.layers[1] = OscillatorLayer {
        waveform: Waveform::Noise,
        level: 0.75,
        detune_cents: 0.0,
    };
    preset.synth.layers[2] = OscillatorLayer {
        waveform: Waveform::Square,
        level: 0.16,
        detune_cents: 7.0,
    };
    preset
}

impl SimpleWaveformSynth {
    pub const PRESETS: &'static [SynthPreset] = &[
        preset!(
            "Bright lead",
            "Lead",
            Waveform::Sawtooth,
            3,
            12.0,
            0.7,
            8.0,
            90.0,
            0.75,
            180.0,
            FilterKind::LowPass,
            7_500.0,
        ),
        preset!(
            "Wide chorus",
            "Lead",
            Waveform::Sawtooth,
            4,
            18.0,
            0.55,
            20.0,
            180.0,
            0.65,
            350.0,
            FilterKind::LowPass,
            5_500.0,
        ),
        preset!(
            "Sub bass",
            "Bass",
            Waveform::Sine,
            1,
            0.0,
            1.0,
            4.0,
            80.0,
            0.9,
            130.0,
            FilterKind::LowPass,
            900.0,
        ),
        preset!(
            "Pluck bass",
            "Bass",
            Waveform::Square,
            2,
            6.0,
            0.65,
            2.0,
            180.0,
            0.15,
            90.0,
            FilterKind::LowPass,
            1_800.0,
        ),
        preset!(
            "808-style kick",
            "Percussion",
            Waveform::Sine,
            1,
            0.0,
            1.0,
            0.0,
            35.0,
            0.0,
            70.0,
            -24,
            FilterKind::LowPass,
            2_500.0,
        ),
        snare_preset(),
        preset!(
            "Closed hi-hat",
            "Percussion",
            Waveform::Noise,
            2,
            20.0,
            0.5,
            0.0,
            22.0,
            0.0,
            35.0,
            FilterKind::HighPass,
            7_500.0,
        ),
        preset!(
            "Noise hit",
            "Percussion",
            Waveform::Noise,
            1,
            0.0,
            0.8,
            0.0,
            55.0,
            0.0,
            100.0,
            FilterKind::HighPass,
            3_500.0,
        ),
        preset!(
            "Soft keys",
            "Acoustic-ish",
            Waveform::Sine,
            2,
            4.0,
            0.7,
            12.0,
            650.0,
            0.45,
            700.0,
            FilterKind::LowPass,
            4_200.0,
        ),
        preset!(
            "Reed",
            "Acoustic-ish",
            Waveform::Square,
            2,
            3.0,
            0.55,
            80.0,
            220.0,
            0.72,
            260.0,
            FilterKind::BandPass,
            2_200.0,
        ),
        preset!(
            "Violin",
            "Orchestra · Strings",
            Waveform::Sawtooth,
            3,
            5.0,
            0.55,
            90.0,
            320.0,
            0.72,
            450.0,
            FilterKind::LowPass,
            4_800.0,
        ),
        preset!(
            "Synth strings",
            "Strings",
            Waveform::Sawtooth,
            4,
            14.0,
            0.45,
            240.0,
            700.0,
            0.68,
            1_100.0,
            FilterKind::LowPass,
            3_600.0,
        ),
        preset!(
            "Ambient pad",
            "Pad",
            Waveform::Sine,
            4,
            12.0,
            0.55,
            900.0,
            1_200.0,
            0.72,
            2_800.0,
            FilterKind::LowPass,
            2_800.0,
        ),
        preset!(
            "Voice-like pad",
            "Pad",
            Waveform::Square,
            3,
            7.0,
            0.4,
            650.0,
            900.0,
            0.66,
            2_200.0,
            FilterKind::BandPass,
            1_250.0,
        ),
        preset!(
            "Piccolo",
            "Orchestra · Woodwinds",
            Waveform::Sine,
            2,
            3.0,
            0.58,
            35.0,
            180.0,
            0.78,
            180.0,
            FilterKind::HighPass,
            1_800.0
        ),
        preset!(
            "Flute",
            "Orchestra · Woodwinds",
            Waveform::Sine,
            2,
            4.0,
            0.62,
            70.0,
            260.0,
            0.82,
            300.0,
            FilterKind::LowPass,
            7_000.0
        ),
        preset!(
            "Oboe",
            "Orchestra · Woodwinds",
            Waveform::Square,
            2,
            2.0,
            0.48,
            65.0,
            180.0,
            0.75,
            260.0,
            FilterKind::BandPass,
            1_800.0
        ),
        preset!(
            "English horn",
            "Orchestra · Woodwinds",
            Waveform::Square,
            2,
            3.0,
            0.5,
            85.0,
            240.0,
            0.78,
            340.0,
            FilterKind::BandPass,
            1_350.0
        ),
        preset!(
            "Clarinet",
            "Orchestra · Woodwinds",
            Waveform::Square,
            2,
            2.0,
            0.52,
            55.0,
            220.0,
            0.8,
            260.0,
            FilterKind::LowPass,
            3_600.0
        ),
        preset!(
            "Bass clarinet",
            "Orchestra · Woodwinds",
            Waveform::Square,
            2,
            3.0,
            0.58,
            70.0,
            260.0,
            0.82,
            360.0,
            -12,
            FilterKind::LowPass,
            2_200.0
        ),
        preset!(
            "Bassoon",
            "Orchestra · Woodwinds",
            Waveform::Sawtooth,
            2,
            3.0,
            0.42,
            70.0,
            250.0,
            0.76,
            320.0,
            FilterKind::BandPass,
            950.0
        ),
        preset!(
            "Contrabassoon",
            "Orchestra · Woodwinds",
            Waveform::Sawtooth,
            2,
            2.0,
            0.5,
            90.0,
            300.0,
            0.8,
            420.0,
            -12,
            FilterKind::LowPass,
            1_100.0
        ),
        preset!(
            "Saxophone",
            "Orchestra · Woodwinds",
            Waveform::Sawtooth,
            3,
            4.0,
            0.42,
            55.0,
            190.0,
            0.72,
            280.0,
            FilterKind::BandPass,
            1_600.0
        ),
        preset!(
            "French horn",
            "Orchestra · Brass",
            Waveform::Sawtooth,
            3,
            4.0,
            0.42,
            110.0,
            320.0,
            0.8,
            480.0,
            FilterKind::LowPass,
            2_300.0
        ),
        preset!(
            "Trumpet",
            "Orchestra · Brass",
            Waveform::Sawtooth,
            3,
            5.0,
            0.48,
            35.0,
            160.0,
            0.78,
            220.0,
            FilterKind::BandPass,
            2_800.0
        ),
        preset!(
            "Cornet",
            "Orchestra · Brass",
            Waveform::Sawtooth,
            2,
            3.0,
            0.5,
            45.0,
            190.0,
            0.78,
            250.0,
            FilterKind::LowPass,
            3_000.0
        ),
        preset!(
            "Tenor trombone",
            "Orchestra · Brass",
            Waveform::Sawtooth,
            3,
            3.0,
            0.48,
            55.0,
            210.0,
            0.8,
            300.0,
            FilterKind::LowPass,
            2_200.0
        ),
        preset!(
            "Bass trombone",
            "Orchestra · Brass",
            Waveform::Sawtooth,
            3,
            3.0,
            0.52,
            70.0,
            260.0,
            0.82,
            380.0,
            -12,
            FilterKind::LowPass,
            1_700.0
        ),
        preset!(
            "Euphonium",
            "Orchestra · Brass",
            Waveform::Sawtooth,
            2,
            3.0,
            0.5,
            80.0,
            270.0,
            0.84,
            400.0,
            FilterKind::LowPass,
            1_900.0
        ),
        preset!(
            "Tuba",
            "Orchestra · Brass",
            Waveform::Sawtooth,
            2,
            2.0,
            0.56,
            90.0,
            320.0,
            0.85,
            450.0,
            -12,
            FilterKind::LowPass,
            1_300.0
        ),
        preset!(
            "Brass ensemble",
            "Orchestra · Brass",
            Waveform::Sawtooth,
            4,
            10.0,
            0.4,
            100.0,
            350.0,
            0.8,
            600.0,
            FilterKind::LowPass,
            2_600.0
        ),
        preset!(
            "Viola",
            "Orchestra · Strings",
            Waveform::Sawtooth,
            3,
            5.0,
            0.52,
            100.0,
            340.0,
            0.74,
            500.0,
            FilterKind::LowPass,
            4_000.0
        ),
        preset!(
            "Cello",
            "Orchestra · Strings",
            Waveform::Sawtooth,
            3,
            4.0,
            0.55,
            120.0,
            380.0,
            0.78,
            600.0,
            -12,
            FilterKind::LowPass,
            3_200.0
        ),
        preset!(
            "Double bass",
            "Orchestra · Strings",
            Waveform::Sawtooth,
            2,
            3.0,
            0.58,
            140.0,
            420.0,
            0.8,
            700.0,
            -24,
            FilterKind::LowPass,
            2_200.0
        ),
        preset!(
            "Harp",
            "Orchestra · Plucked and keys",
            Waveform::Sine,
            3,
            5.0,
            0.5,
            2.0,
            900.0,
            0.0,
            1_200.0,
            FilterKind::LowPass,
            6_000.0
        ),
        preset!(
            "Grand piano",
            "Orchestra · Plucked and keys",
            Waveform::Sine,
            3,
            7.0,
            0.52,
            2.0,
            750.0,
            0.18,
            900.0,
            FilterKind::LowPass,
            5_500.0
        ),
        preset!(
            "Celesta",
            "Orchestra · Plucked and keys",
            Waveform::Sine,
            2,
            8.0,
            0.55,
            1.0,
            600.0,
            0.0,
            700.0,
            12,
            FilterKind::HighPass,
            1_300.0
        ),
        preset!(
            "Harpsichord",
            "Orchestra · Plucked and keys",
            Waveform::Square,
            2,
            3.0,
            0.45,
            0.0,
            260.0,
            0.0,
            160.0,
            FilterKind::HighPass,
            650.0
        ),
        preset!(
            "Timpani",
            "Orchestra · Tuned percussion",
            Waveform::Sine,
            2,
            9.0,
            0.7,
            0.0,
            900.0,
            0.0,
            1_100.0,
            -12,
            FilterKind::LowPass,
            1_100.0
        ),
        preset!(
            "Glockenspiel",
            "Orchestra · Tuned percussion",
            Waveform::Sine,
            3,
            14.0,
            0.5,
            0.0,
            700.0,
            0.0,
            900.0,
            24,
            FilterKind::HighPass,
            2_000.0
        ),
        preset!(
            "Xylophone",
            "Orchestra · Tuned percussion",
            Waveform::Square,
            2,
            7.0,
            0.42,
            0.0,
            180.0,
            0.0,
            120.0,
            12,
            FilterKind::BandPass,
            2_400.0
        ),
        preset!(
            "Marimba",
            "Orchestra · Tuned percussion",
            Waveform::Sine,
            2,
            5.0,
            0.62,
            0.0,
            520.0,
            0.0,
            600.0,
            FilterKind::LowPass,
            2_800.0
        ),
        preset!(
            "Vibraphone",
            "Orchestra · Tuned percussion",
            Waveform::Sine,
            3,
            9.0,
            0.5,
            0.0,
            1_300.0,
            0.2,
            1_600.0,
            FilterKind::LowPass,
            5_000.0
        ),
        preset!(
            "Tubular bells",
            "Orchestra · Tuned percussion",
            Waveform::Sine,
            4,
            18.0,
            0.38,
            0.0,
            1_500.0,
            0.0,
            2_000.0,
            FilterKind::HighPass,
            900.0
        ),
        preset!(
            "Concert bass drum",
            "Orchestra · Percussion",
            Waveform::Sine,
            2,
            12.0,
            0.75,
            0.0,
            500.0,
            0.0,
            650.0,
            -24,
            FilterKind::LowPass,
            900.0
        ),
        preset!(
            "Field drum",
            "Orchestra · Percussion",
            Waveform::Noise,
            3,
            8.0,
            0.5,
            0.0,
            180.0,
            0.0,
            120.0,
            FilterKind::BandPass,
            2_400.0
        ),
        preset!(
            "Crash cymbal",
            "Orchestra · Percussion",
            Waveform::Noise,
            3,
            18.0,
            0.45,
            0.0,
            1_200.0,
            0.0,
            1_500.0,
            FilterKind::HighPass,
            3_200.0
        ),
        preset!(
            "Tam-tam",
            "Orchestra · Percussion",
            Waveform::Noise,
            4,
            24.0,
            0.4,
            0.0,
            1_800.0,
            0.0,
            2_400.0,
            FilterKind::BandPass,
            900.0
        ),
        preset!(
            "Triangle",
            "Orchestra · Percussion",
            Waveform::Sine,
            3,
            28.0,
            0.42,
            0.0,
            900.0,
            0.0,
            1_200.0,
            36,
            FilterKind::HighPass,
            4_000.0
        ),
        preset!(
            "Tambourine",
            "Orchestra · Percussion",
            Waveform::Noise,
            3,
            15.0,
            0.45,
            0.0,
            260.0,
            0.0,
            220.0,
            FilterKind::HighPass,
            4_500.0
        ),
        preset!(
            "Woodblock",
            "Orchestra · Percussion",
            Waveform::Square,
            2,
            9.0,
            0.5,
            0.0,
            90.0,
            0.0,
            70.0,
            12,
            FilterKind::BandPass,
            1_800.0
        ),
        preset!(
            "Castanets",
            "Orchestra · Percussion",
            Waveform::Noise,
            2,
            8.0,
            0.5,
            0.0,
            55.0,
            0.0,
            45.0,
            FilterKind::HighPass,
            3_800.0
        ),
    ];
}

